from dataclasses import dataclass

@dataclass   # Dataclass decorator generates boilerplate code
class Person:  # Define normal class
    first_name: str  # Define fields with their types (can use typing module)
    last_name: str
    city: str
    state: str


if __name__ == '__main__':
    person = Person('Joe', 'Schmoe', 'Schenectady', 'NY')  # Create instance of dataclass
    print("using fields:", person.first_name, person.last_name)
    print("repr:", repr(person))  # Access by fields, repr() method is autogenerated
    person.last_name = 'Smith' # Fields are read/write by default
    print("after changing last name:", person)
